import { test, expect } from '@playwright/test'
test('topic → brief → reload → follow-up → version → export and history', async ({ page }, testInfo) => {
  const consoleErrors: string[] = []
  page.on('pageerror', error => consoleErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /从一个问题开始，\s*找到有来源的答案。/ })).toBeVisible()
  await page.getByLabel('你想研究什么？').fill('Node.js 支持周期')
  await page.getByRole('button', { name: '开始研究', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Node.js 支持周期（模拟资料）', exact: true })).toBeVisible()
  await expect(page.getByText('本轮已读取', { exact: true })).toHaveCount(2)
  await page.screenshot({ path: `.impeccable/review/${testInfo.project.name}.png`, fullPage: true, scale: 'css' })
  const url = page.url()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Node.js 支持周期（模拟资料）', exact: true })).toBeVisible()
  await page.getByLabel('继续研究', { exact: true }).fill('更新简报：补充版本选择依据')
  await page.getByRole('button', { name: '发送追问' }).click()
  await expect(page.getByRole('heading', { name: '更新的研究简报（模拟资料）' })).toBeVisible()
  await page.getByLabel('简报版本').selectOption({ label: '第 1 版' })
  await expect(page.getByRole('heading', { name: 'Node.js 支持周期（模拟资料）', exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: '导出 Markdown' }).click()
  const download = await downloadPromise
  const content = await (await download.createReadStream())!.toArray()
  expect(Buffer.concat(content).toString()).toContain('## 来源')
  expect(download.suggestedFilename()).toBe('Node.js 支持周期.md')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: '研究历史', exact: true }).click()
  await page.getByRole('button', { name: '新研究' }).click()
  await page.getByLabel('你想研究什么？').fill('第二个独立主题')
  await page.getByRole('button', { name: '开始研究', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Node.js 支持周期（模拟资料）', exact: true })).toBeVisible()
  await page.goto(url)
  await expect(page.getByLabel('简报版本')).toBeVisible()
  await page.getByRole('button', { name: /对话记录/ }).click()
  await expect(page.getByText('你的问题', { exact: true })).toHaveCount(2)
  expect(consoleErrors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
