import { test, expect } from '@playwright/test'
test('topic → brief → reload → follow-up → version → export and history', async ({ page }, testInfo) => {
  const consoleErrors: string[] = []
  page.on('pageerror', error => consoleErrors.push(error.message))
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.getByRole('heading', { name: /Start with a question.\s*Build an answer with sources./ })).toBeVisible()
  await page.locator('.sdk-debug > summary').click()
  await expect(page.getByText('Agent ID', { exact: true })).toBeVisible()
  await expect(page.getByText('Simulated mode:', { exact: false })).toBeVisible()
  await page.getByLabel('What would you like to research?').fill('Node.js support timelines')
  await page.getByRole('button', { name: 'Start research', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Node.js support timelines (simulated sources)', exact: true })).toBeVisible()
  await expect(page.getByText('Read in this run', { exact: true })).toHaveCount(2)
  await expect(page.getByRole('list', { name: 'SDK call log' }).getByText('postEvents', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Show history and status reads' }).uncheck()
  await page.getByRole('list', { name: 'SDK call log' }).locator('li').filter({ hasText: 'postEvents' }).getByText('Arguments and results', { exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `.impeccable/review/debug-calls-${testInfo.project.name}.png`, fullPage: true, scale: 'css' })
  const sdkTab = page.getByRole('tab', { name: 'SDK calls', exact: true })
  const eventTab = page.getByRole('tab', { name: 'Platform events', exact: true })
  await sdkTab.focus(); await sdkTab.press('ArrowRight')
  await expect(eventTab).toBeFocused()
  await expect(eventTab).toHaveAttribute('aria-selected', 'true')
  await expect(eventTab).toHaveAttribute('tabindex', '0')
  await expect(sdkTab).toHaveAttribute('tabindex', '-1')
  await expect(page.locator('#debug-calls')).toHaveCount(1)
  await expect(page.locator('#debug-calls')).toBeHidden()
  await eventTab.press('Home')
  await expect(sdkTab).toBeFocused()
  await sdkTab.press('End')
  await expect(eventTab).toBeFocused()
  await expect(page.getByRole('list', { name: 'Platform event log' }).getByText('web_fetch', { exact: true })).toHaveCount(4)
  await page.getByRole('button', { name: 'Pause display', exact: true }).click()
  await expect(page.getByText('Display paused', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `.impeccable/review/debug-${testInfo.project.name}.png`, fullPage: true, scale: 'css' })
  await page.getByRole('button', { name: 'Resume display', exact: true }).click()
  await page.getByRole('tab', { name: 'SDK calls', exact: true }).click()
  await page.locator('.sdk-debug > summary').click()
  await page.screenshot({ path: `.impeccable/review/${testInfo.project.name}.png`, fullPage: true, scale: 'css' })
  const url = page.url()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Node.js support timelines (simulated sources)', exact: true })).toBeVisible()
  await page.getByLabel('Continue research', { exact: true }).fill('Update the brief: add version selection criteria')
  await page.getByRole('button', { name: 'Send follow-up' }).click()
  await expect(page.getByRole('heading', { name: 'Updated research brief (simulated sources)' })).toBeVisible()
  await page.getByLabel('Brief version').selectOption({ label: 'Version 1' })
  await expect(page.getByRole('heading', { name: 'Node.js support timelines (simulated sources)', exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Export Markdown' }).click()
  const download = await downloadPromise
  const content = await (await download.createReadStream())!.toArray()
  expect(Buffer.concat(content).toString()).toContain('## Sources')
  expect(download.suggestedFilename()).toBe('Node.js support timelines.md')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: 'Research history', exact: true }).click()
  await page.getByRole('button', { name: 'New research' }).click()
  await page.getByLabel('What would you like to research?').fill('A second independent topic')
  await page.getByRole('button', { name: 'Start research', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Node.js support timelines (simulated sources)', exact: true })).toBeVisible()
  await page.goto(url)
  await expect(page.getByLabel('Brief version')).toBeVisible()
  await page.getByRole('button', { name: /Conversation/ }).click()
  await expect(page.getByText('Your question', { exact: true })).toHaveCount(2)
  expect(await page.locator('body').innerText()).not.toMatch(/[\p{Script=Han}]/u)
  expect(consoleErrors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
